name: .NET

on:
  push:
    branches: [ master ]
    paths: Favohit.WebApi/**
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Favohit.WebApi/Favohit.WebApi.csproj
    - name: Build
      run: dotnet build Favohit.WebApi/Favohit.WebApi.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test Favohit.WebApi/Favohit.WebApi.csproj --no-build --verbosity normal
